name: Deploy Production

# listen to push and pull request events
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

# tasks to run when the event is triggered
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
          cache: 'npm'
      - name: Create .env file
        run:
          echo "${{ secrets.ENV_PRODUCTION }}" > .env
      - run: npm i --force
      - run: npm run build
  # normally, there will be a test step here before deploying
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh command using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script:
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/nextjs-free
            git fetch --all
            git reset --hard origin/main
            echo "${{ secrets.ENV_PRODUCTION }}" > .env
            npm i --force
            npx prisma generate
            npm run build
            pm2 restart Fastify




